### PR TITLE
Setup Travis CI

### PR DESCRIPTION
**Pull request by akagomez**
Also testing Travis.

### CODE REVIEW

**Comment by daffl** [comment]
You may want to use `"testee": "^0.2.0"` to get the latest version. That should most likely fix the error although I'd verify that it works locally by cleaning the NPM cache, making a fresh clone and running `npm install && npm test`.

**Comment by akagomez** [comment]
@daffl I may need your help with Testee. I'm getting this error locally: 

```
  Missing error handler on `socket`.
TypeError: info.emitters(...).forEach is not a function
    at Object.<anonymous> (/Users/akagomez/Sites/bitovi/can_derive_fresh/node_modules/testee/node_modules/feathers/lib/providers/socket/commons.js:46:21)
    at emitOne (events.js:82:20)
    at Object.emit (events.js:169:7)
    at EventEmitter.<anonymous> (/Users/akagomez/Sites/bitovi/can_derive_fresh/node_modules/testee/node_modules/feathers/lib/mixins/event.js:41:18)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at Object.exports.emitEvents (/Users/akagomez/Sites/bitovi/can_derive_fresh/node_modules/testee/node_modules/feathers/node_modules/rubberduck/lib/utils.js:32:18)
    at callbackWrapper (/Users/akagomez/Sites/bitovi/can_derive_fresh/node_modules/testee/node_modules/feathers/node_modules/rubberduck/lib/rubberduck.js:56:15)
    at Object.Proto.extend.create (/Users/akagomez/Sites/bitovi/can_derive_fresh/node_modules/testee/node_modules/feathers-memory/lib/memory.js:79:5)
    at Object.self.(anonymous function) (/Users/akagomez/Sites/bitovi/can_derive_fresh/node_modules/testee/node_modules/feathers-memory/node_modules/uberproto/lib/proto.js:61:21)
```

**Comment by daffl** [comment]
I just verified that it works with Testee 0.2.4 so you just need to change the dependency matcher like I mentioned. Tests are all failing for me either way though.
